"""Baseline production schema.

Every domain table as of the Vercel/Supabase migration, generated from the
SQLAlchemy models. Those models remain the single authority for this schema;
RLS, storage buckets/policies and queues are owned by supabase/migrations.

Revision ID: 3f02eee26aa9
Revises: 
Create Date: 2026-08-26 23:32:02.555627
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # referenced by the JSONB variants below
from sqlalchemy.dialects import postgresql

revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('pipeline_version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('source_asset_id', sa.String(), nullable=True),
    sa.Column('analysis_asset_id', sa.String(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('failed_stage', sa.String(), nullable=True),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('configuration', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_runs_error_code'), ['error_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_heartbeat_at'), ['heartbeat_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_lease_expires_at'), ['lease_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_pipeline_version'), ['pipeline_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_status'), ['status'], unique=False)
        batch_op.create_index('ix_analysis_runs_status_lease', ['status', 'lease_expires_at'], unique=False)
        batch_op.create_index('ix_analysis_runs_video_created', ['video_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_video_id'), ['video_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_worker_id'), ['worker_id'], unique=False)

    op.create_table('annotations',
    sa.Column('training_asset_id', sa.String(), nullable=False),
    sa.Column('annotator_user_id', sa.String(), nullable=False),
    sa.Column('annotation_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotations_training_asset_id'), ['training_asset_id'], unique=False)

    op.create_table('api_keys',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('key_prefix', sa.String(), nullable=False),
    sa.Column('scopes', sa.String(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_keys_user_id'), ['user_id'], unique=False)

    op.create_table('calibration',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('homography_matrix', sa.JSON(), nullable=True),
    sa.Column('court_corners_px', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calibration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calibration_video_id'), ['video_id'], unique=False)

    op.create_table('challenges',
    sa.Column('created_by_user_id', sa.String(), nullable=False),
    sa.Column('opponent_user_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenges_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenges_opponent_user_id'), ['opponent_user_id'], unique=False)

    op.create_table('club_memberships',
    sa.Column('club_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('club_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_club_memberships_club_id'), ['club_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_club_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('clubs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clubs_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('coach_notes',
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('coach_user_id', sa.String(), nullable=False),
    sa.Column('timestamp_s', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('related_insight_id', sa.String(), nullable=True),
    sa.Column('stance', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coach_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coach_notes_coach_user_id'), ['coach_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coach_notes_review_id'), ['review_id'], unique=False)
        batch_op.create_index('ix_coach_notes_video_created', ['video_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_coach_notes_video_id'), ['video_id'], unique=False)

    op.create_table('coach_reviews',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('student_user_id', sa.String(), nullable=False),
    sa.Column('coach_user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coach_reviews', schema=None) as batch_op:
        batch_op.create_index('ix_coach_reviews_coach_status', ['coach_user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_coach_reviews_coach_user_id'), ['coach_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coach_reviews_student_user_id'), ['student_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coach_reviews_video_id'), ['video_id'], unique=False)
        batch_op.create_index('ix_coach_reviews_video_status', ['video_id', 'status'], unique=False)

    op.create_table('coaching_insights',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('tracked_person_id', sa.String(), nullable=False),
    sa.Column('related_shot_id', sa.String(), nullable=True),
    sa.Column('timestamp_s', sa.Float(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('observed_action', sa.Text(), nullable=False),
    sa.Column('likely_impact', sa.Text(), nullable=False),
    sa.Column('correction', sa.Text(), nullable=False),
    sa.Column('drill_id', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('limitations', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coaching_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coaching_insights_tracked_person_id'), ['tracked_person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coaching_insights_video_id'), ['video_id'], unique=False)
        batch_op.create_index('ix_insights_video_timestamp', ['video_id', 'timestamp_s'], unique=False)

    op.create_table('consent_records',
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('consenting_party', sa.String(), nullable=False),
    sa.Column('consent_text_snapshot', sa.Text(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_records_subject_id'), ['subject_id'], unique=False)

    op.create_table('consent_settings',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('allow_training_data_contribution', sa.Boolean(), nullable=False),
    sa.Column('default_clip_share_scope', sa.String(), nullable=False),
    sa.Column('default_profile_share_scope', sa.String(), nullable=False),
    sa.Column('retention_policy', sa.String(), nullable=False),
    sa.Column('share_progress_with_club', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_settings_user_id'), ['user_id'], unique=True)

    op.create_table('drills',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_issue_tags', sa.JSON(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendships',
    sa.Column('user_id_a', sa.String(), nullable=False),
    sa.Column('user_id_b', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friendships_user_id_a'), ['user_id_a'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_user_id_b'), ['user_id_b'], unique=False)

    op.create_table('match_analytics',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('feature_version', sa.String(), nullable=False),
    sa.Column('analytics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_analytics_video_id'), ['video_id'], unique=True)

    op.create_table('one_time_tokens',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('one_time_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_one_time_tokens_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_one_time_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_one_time_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('player_profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('matches_analyzed_count', sa.Integer(), nullable=False),
    sa.Column('play_style_labels', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('strengths', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('weaknesses', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('radar_scores', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('training_plan', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('pose_frames',
    sa.Column('tracked_person_id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=False),
    sa.Column('timestamp_s', sa.Float(), nullable=False),
    sa.Column('landmarks', sa.JSON(), nullable=False),
    sa.Column('stance_label', sa.String(), nullable=False),
    sa.Column('balance_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pose_frames', schema=None) as batch_op:
        batch_op.create_index('ix_pose_frames_person_frame', ['tracked_person_id', 'frame_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_pose_frames_tracked_person_id'), ['tracked_person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pose_frames_video_id'), ['video_id'], unique=False)

    op.create_table('practice_plans',
    sa.Column('created_by_user_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('participants', sa.JSON(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('linked_drill_ids', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_plans_created_by_user_id'), ['created_by_user_id'], unique=False)

    op.create_table('processing_events',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('analysis_run_id', sa.String(), nullable=True),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_events_analysis_run_id'), ['analysis_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_events_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index('ix_processing_events_video_created', ['video_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_events_video_id'), ['video_id'], unique=False)

    op.create_table('processing_jobs',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_jobs_video_id'), ['video_id'], unique=False)

    op.create_table('profile_history_snapshots',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), nullable=False),
    sa.Column('radar_scores', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile_history_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_history_snapshots_user_id'), ['user_id'], unique=False)

    op.create_table('rallies',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('rally_index', sa.Integer(), nullable=False),
    sa.Column('phases', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('ending_shot_type', sa.String(), nullable=True),
    sa.Column('ending_track_role', sa.String(), nullable=True),
    sa.Column('start_frame', sa.Integer(), nullable=False),
    sa.Column('end_frame', sa.Integer(), nullable=False),
    sa.Column('start_timestamp_s', sa.Float(), nullable=False),
    sa.Column('end_timestamp_s', sa.Float(), nullable=False),
    sa.Column('shot_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rallies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rallies_video_id'), ['video_id'], unique=False)
        batch_op.create_index('ix_rallies_video_index', ['video_id', 'rally_index'], unique=False)

    op.create_table('shared_clips',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('created_by_user_id', sa.String(), nullable=False),
    sa.Column('clip_start_s', sa.Float(), nullable=False),
    sa.Column('clip_end_s', sa.Float(), nullable=False),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shared_clips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shared_clips_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shared_clips_video_id'), ['video_id'], unique=False)

    op.create_table('shots',
    sa.Column('rally_id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('tracked_person_id', sa.String(), nullable=False),
    sa.Column('shot_index_in_rally', sa.Integer(), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=False),
    sa.Column('timestamp_s', sa.Float(), nullable=False),
    sa.Column('shot_type', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('contact_height', sa.String(), nullable=False),
    sa.Column('intent', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shots_rally_id'), ['rally_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shots_tracked_person_id'), ['tracked_person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shots_video_id'), ['video_id'], unique=False)
        batch_op.create_index('ix_shots_video_timestamp', ['video_id', 'timestamp_s'], unique=False)

    op.create_table('shuttle_frames',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=False),
    sa.Column('timestamp_s', sa.Float(), nullable=False),
    sa.Column('position_px', sa.JSON(), nullable=True),
    sa.Column('position_court', sa.JSON(), nullable=True),
    sa.Column('estimated_speed_mps', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shuttle_frames', schema=None) as batch_op:
        batch_op.create_index('ix_shuttle_frames_video_frame', ['video_id', 'frame_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_shuttle_frames_video_id'), ['video_id'], unique=False)

    op.create_table('storage_usage',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('original_bytes', sa.BigInteger(), nullable=False),
    sa.Column('derived_bytes', sa.BigInteger(), nullable=False),
    sa.Column('asset_count', sa.Integer(), nullable=False),
    sa.Column('last_reconciled_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('storage_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storage_usage_user_id'), ['user_id'], unique=True)

    op.create_table('technique_references',
    sa.Column('shot_or_movement_name', sa.String(), nullable=False),
    sa.Column('singles_or_doubles_context', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('phases', sa.JSON(), nullable=False),
    sa.Column('common_beginner_mistakes', sa.JSON(), nullable=False),
    sa.Column('advanced_variations', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('checkpoints', sa.JSON(), nullable=False),
    sa.Column('level_notes', sa.JSON(), nullable=False),
    sa.Column('context_notes', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('technique_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technique_references_shot_or_movement_name'), ['shot_or_movement_name'], unique=False)

    op.create_table('tracked_persons',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('bounding_boxes', sa.JSON(), nullable=False),
    sa.Column('first_frame', sa.Integer(), nullable=False),
    sa.Column('last_frame', sa.Integer(), nullable=False),
    sa.Column('track_confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracked_persons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracked_persons_video_id'), ['video_id'], unique=False)

    op.create_table('training_assets',
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url_or_reference', sa.String(), nullable=True),
    sa.Column('license_type', sa.String(), nullable=True),
    sa.Column('license_terms_url', sa.String(), nullable=True),
    sa.Column('usage_restrictions', sa.Text(), nullable=True),
    sa.Column('rights_holder', sa.String(), nullable=True),
    sa.Column('consent_record_id', sa.String(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.Column('added_by_user_id', sa.String(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload_sessions',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('upload_method', sa.String(), nullable=False),
    sa.Column('storage_bucket', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('expected_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('received_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('declared_content_type', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upload_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_upload_sessions_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_sessions_video_id'), ['video_id'], unique=False)

    op.create_table('user_corrections',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('correction_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_corrections_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_corrections_video_id'), ['video_id'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('tokens_valid_from', sa.DateTime(), nullable=True),
    sa.Column('auth_provider', sa.String(), nullable=False),
    sa.Column('supabase_user_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_auth_provider'), ['auth_provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_supabase_user_id'), ['supabase_user_id'], unique=True)

    op.create_table('video_assets',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('storage_bucket', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('codec', sa.String(), nullable=True),
    sa.Column('container', sa.String(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('transform_version', sa.String(), nullable=True),
    sa.Column('source_asset_id', sa.String(), nullable=True),
    sa.Column('source_checksum', sa.String(length=64), nullable=True),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_assets_asset_type'), ['asset_type'], unique=False)
        batch_op.create_index('ix_video_assets_bucket_path', ['storage_bucket', 'storage_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_assets_checksum_sha256'), ['checksum_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_assets_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_video_assets_owner_live', ['owner_user_id', 'deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_assets_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_assets_source_asset_id'), ['source_asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_assets_video_id'), ['video_id'], unique=False)
        batch_op.create_index('ix_video_assets_video_type', ['video_id', 'asset_type'], unique=False)

    op.create_table('videos',
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('resolution_w', sa.Integer(), nullable=True),
    sa.Column('resolution_h', sa.Integer(), nullable=True),
    sa.Column('match_format', sa.String(), nullable=False),
    sa.Column('opponent_name', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('camera_view_hint', sa.String(), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.String(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('quality_report', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('pipeline_version', sa.String(), nullable=True),
    sa.Column('storage_bucket', sa.String(), nullable=True),
    sa.Column('storage_key', sa.String(), nullable=True),
    sa.Column('source_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('source_container', sa.String(), nullable=True),
    sa.Column('source_video_codec', sa.String(), nullable=True),
    sa.Column('source_audio_codec', sa.String(), nullable=True),
    sa.Column('source_rotation', sa.Integer(), nullable=True),
    sa.Column('source_bitrate', sa.BigInteger(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('analysis_confidence', sa.Float(), nullable=True),
    sa.Column('current_analysis_run_id', sa.String(), nullable=True),
    sa.Column('processing_error_code', sa.String(), nullable=True),
    sa.Column('processing_error_retryable', sa.Boolean(), nullable=False),
    sa.Column('failed_stage', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('original_retained_until', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_checksum_sha256'), ['checksum_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_videos_owner_checksum', ['owner_user_id', 'checksum_sha256'], unique=False)
        batch_op.create_index('ix_videos_owner_created', ['owner_user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_videos_owner_status', ['owner_user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index('ix_videos_status_updated', ['status', 'updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index('ix_videos_status_updated')
        batch_op.drop_index(batch_op.f('ix_videos_owner_user_id'))
        batch_op.drop_index('ix_videos_owner_status')
        batch_op.drop_index('ix_videos_owner_created')
        batch_op.drop_index('ix_videos_owner_checksum')
        batch_op.drop_index(batch_op.f('ix_videos_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_videos_checksum_sha256'))

    op.drop_table('videos')
    with op.batch_alter_table('video_assets', schema=None) as batch_op:
        batch_op.drop_index('ix_video_assets_video_type')
        batch_op.drop_index(batch_op.f('ix_video_assets_video_id'))
        batch_op.drop_index(batch_op.f('ix_video_assets_source_asset_id'))
        batch_op.drop_index(batch_op.f('ix_video_assets_owner_user_id'))
        batch_op.drop_index('ix_video_assets_owner_live')
        batch_op.drop_index(batch_op.f('ix_video_assets_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_video_assets_checksum_sha256'))
        batch_op.drop_index('ix_video_assets_bucket_path')
        batch_op.drop_index(batch_op.f('ix_video_assets_asset_type'))

    op.drop_table('video_assets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_supabase_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_auth_provider'))

    op.drop_table('users')
    with op.batch_alter_table('user_corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_corrections_video_id'))
        batch_op.drop_index(batch_op.f('ix_user_corrections_user_id'))

    op.drop_table('user_corrections')
    with op.batch_alter_table('upload_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_sessions_video_id'))
        batch_op.drop_index('ix_upload_sessions_user_status')
        batch_op.drop_index(batch_op.f('ix_upload_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_upload_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_upload_sessions_expires_at'))

    op.drop_table('upload_sessions')
    op.drop_table('training_assets')
    with op.batch_alter_table('tracked_persons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracked_persons_video_id'))

    op.drop_table('tracked_persons')
    with op.batch_alter_table('technique_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technique_references_shot_or_movement_name'))

    op.drop_table('technique_references')
    with op.batch_alter_table('storage_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storage_usage_user_id'))

    op.drop_table('storage_usage')
    with op.batch_alter_table('shuttle_frames', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shuttle_frames_video_id'))
        batch_op.drop_index('ix_shuttle_frames_video_frame')

    op.drop_table('shuttle_frames')
    with op.batch_alter_table('shots', schema=None) as batch_op:
        batch_op.drop_index('ix_shots_video_timestamp')
        batch_op.drop_index(batch_op.f('ix_shots_video_id'))
        batch_op.drop_index(batch_op.f('ix_shots_tracked_person_id'))
        batch_op.drop_index(batch_op.f('ix_shots_rally_id'))

    op.drop_table('shots')
    with op.batch_alter_table('shared_clips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shared_clips_video_id'))
        batch_op.drop_index(batch_op.f('ix_shared_clips_created_by_user_id'))

    op.drop_table('shared_clips')
    with op.batch_alter_table('rallies', schema=None) as batch_op:
        batch_op.drop_index('ix_rallies_video_index')
        batch_op.drop_index(batch_op.f('ix_rallies_video_id'))

    op.drop_table('rallies')
    with op.batch_alter_table('profile_history_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_history_snapshots_user_id'))

    op.drop_table('profile_history_snapshots')
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_jobs_video_id'))

    op.drop_table('processing_jobs')
    with op.batch_alter_table('processing_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_events_video_id'))
        batch_op.drop_index('ix_processing_events_video_created')
        batch_op.drop_index(batch_op.f('ix_processing_events_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_processing_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_processing_events_analysis_run_id'))

    op.drop_table('processing_events')
    with op.batch_alter_table('practice_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_plans_created_by_user_id'))

    op.drop_table('practice_plans')
    with op.batch_alter_table('pose_frames', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pose_frames_video_id'))
        batch_op.drop_index(batch_op.f('ix_pose_frames_tracked_person_id'))
        batch_op.drop_index('ix_pose_frames_person_frame')

    op.drop_table('pose_frames')
    with op.batch_alter_table('player_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_profiles_user_id'))

    op.drop_table('player_profiles')
    with op.batch_alter_table('one_time_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_one_time_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_one_time_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_one_time_tokens_purpose'))

    op.drop_table('one_time_tokens')
    with op.batch_alter_table('match_analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_analytics_video_id'))

    op.drop_table('match_analytics')
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friendships_user_id_b'))
        batch_op.drop_index(batch_op.f('ix_friendships_user_id_a'))

    op.drop_table('friendships')
    op.drop_table('drills')
    with op.batch_alter_table('consent_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_settings_user_id'))

    op.drop_table('consent_settings')
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_records_subject_id'))

    op.drop_table('consent_records')
    with op.batch_alter_table('coaching_insights', schema=None) as batch_op:
        batch_op.drop_index('ix_insights_video_timestamp')
        batch_op.drop_index(batch_op.f('ix_coaching_insights_video_id'))
        batch_op.drop_index(batch_op.f('ix_coaching_insights_tracked_person_id'))

    op.drop_table('coaching_insights')
    with op.batch_alter_table('coach_reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_coach_reviews_video_status')
        batch_op.drop_index(batch_op.f('ix_coach_reviews_video_id'))
        batch_op.drop_index(batch_op.f('ix_coach_reviews_student_user_id'))
        batch_op.drop_index(batch_op.f('ix_coach_reviews_coach_user_id'))
        batch_op.drop_index('ix_coach_reviews_coach_status')

    op.drop_table('coach_reviews')
    with op.batch_alter_table('coach_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coach_notes_video_id'))
        batch_op.drop_index('ix_coach_notes_video_created')
        batch_op.drop_index(batch_op.f('ix_coach_notes_review_id'))
        batch_op.drop_index(batch_op.f('ix_coach_notes_coach_user_id'))

    op.drop_table('coach_notes')
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clubs_owner_user_id'))

    op.drop_table('clubs')
    with op.batch_alter_table('club_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_club_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_club_memberships_club_id'))

    op.drop_table('club_memberships')
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenges_opponent_user_id'))
        batch_op.drop_index(batch_op.f('ix_challenges_created_by_user_id'))

    op.drop_table('challenges')
    with op.batch_alter_table('calibration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calibration_video_id'))

    op.drop_table('calibration')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))

    op.drop_table('api_keys')
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotations_training_asset_id'))

    op.drop_table('annotations')
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_runs_worker_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_video_id'))
        batch_op.drop_index('ix_analysis_runs_video_created')
        batch_op.drop_index('ix_analysis_runs_status_lease')
        batch_op.drop_index(batch_op.f('ix_analysis_runs_status'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_pipeline_version'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_lease_expires_at'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_heartbeat_at'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_error_code'))

    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
