"""Seeds system-owned coaching content: technique references (Comparison
Studio) and the drill library. Idempotent — safe to run multiple times.

V2 expands the reference library to the full shot/movement list and adds
per-phase checkpoints, level notes, and tactical-context notes. Content was
written to reflect widely-taught badminton fundamentals; a qualified coach
should review before commercial launch (see docs/V2_DESIGN.md §12).
"""
from app.db.session import SessionLocal, Base, engine
import app.models  # noqa: F401 ensures all tables are registered
from app.models.coaching_content import Drill, TechniqueReference


def _ref(name, summary, phases, mistakes, variations, category="shot",
         checkpoints=None, level_notes=None, context_notes=None, ctx="both"):
    return {
        "shot_or_movement_name": name,
        "singles_or_doubles_context": ctx,
        "summary": summary,
        "phases": [{"phase": p[0], "description": p[1]} for p in phases],
        "common_beginner_mistakes": mistakes,
        "advanced_variations": variations,
        "category": category,
        "checkpoints": checkpoints or [],
        "level_notes": level_notes or {},
        "context_notes": context_notes or {},
    }


STANDARD_LEVELS = {
    "beginner": "Focus on the movement shape at slow speed — accuracy of positions before any power or deception.",
    "intermediate": "Add speed and consistency: same contact point every time, recovery built into the stroke.",
    "advanced": "Work on disguise (identical preparation across shots) and taking the shuttle earlier.",
}

TECHNIQUE_REFERENCES = [
    _ref("high_serve",
         "A deep, high serve pushing the receiver to the back of the court — the staple singles serve.",
         [("Stance", "Feet split front-back, weight on the back foot, shuttle held at the tip by the feathers."),
          ("Drop & swing", "Release the shuttle and swing under it with a relaxed full underarm action."),
          ("Contact", "Below waist height (legal), out in front of the body, face slightly open."),
          ("Follow-through", "Racket finishes high over the opposite shoulder; weight transfers to the front foot."),
          ("Reset", "Step back to a central base immediately — deep serves come back deep.")],
         ["Contact too close to the body, cramping the swing.", "Serving flat instead of high, giving an easy attack.", "Watching the serve instead of resetting."],
         ["Vary depth between the two back corners with the same action."],
         checkpoints=["Weight starts on back foot", "Contact below waist, in front", "Full relaxed follow-through", "Immediate reset to base"],
         level_notes=STANDARD_LEVELS, ctx="singles"),
    _ref("low_serve",
         "A short serve skimming the net tape, landing near the front service line — the staple doubles serve.",
         [("Stance", "Compact stance close to the front service line, racket foot forward."),
          ("Preparation", "Short backswing, shuttle held on the racket side, thumb ready to push (backhand version)."),
          ("Contact", "Gentle push contact below waist height; the shuttle should peak *before* the net."),
          ("Freeze & ready", "Minimal follow-through, racket straight back up for the return drive.")],
         ["Pushing too hard so the shuttle sits up above tape height.", "Long backswing that telegraphs and adds error.", "Dropping the racket after serving."],
         ["Flick variation off the same preparation to punish receivers who crowd the net."],
         checkpoints=["Shuttle peaks before the net", "Tape-height crossing", "Racket up immediately after"],
         level_notes=STANDARD_LEVELS, ctx="doubles"),
    _ref("flick_serve",
         "A deceptive serve using low-serve preparation but flicking the shuttle fast and flat over the receiver.",
         [("Disguise", "Identical stance and preparation to your low serve — the deception is the whole point."),
          ("Wrist acceleration", "At the last moment, accelerate with wrist/forearm instead of a gentle push."),
          ("Trajectory", "Fast, just out of the receiver's reach, landing near the doubles long service line."),
          ("Recovery", "Expect the return earlier than a high serve — get the racket up immediately.")],
         ["Preparation visibly different from the low serve, killing the disguise.", "Flicking too high, turning it into a weak high serve."],
         ["Directional variation: flick to the body vs. the far corner."],
         checkpoints=["Same preparation as low serve", "Late wrist acceleration", "Flat trajectory past receiver's reach"],
         level_notes=STANDARD_LEVELS),
    _ref("serve_return",
         "The receiving stance and first action against serves — attacking short serves and neutralizing flicks.",
         [("Ready stance", "Front-back split, weight forward on the balls of the feet, racket up in front."),
          ("Read", "Watch the server's racket face and contact, not the shuttle flight."),
          ("Short serve response", "Attack the tape: push to the body or tap down if it sits up."),
          ("Flick response", "Push back off the front foot, take it overhead as early as possible.")],
         ["Standing flat-footed at contact.", "Racket held low, conceding the net.", "Committing forward before the serve is struck."],
         ["Deceptive holds at the net off short-serve returns."],
         checkpoints=["Racket up before serve contact", "Weight forward, not planted", "First move at (not after) opponent contact"],
         level_notes=STANDARD_LEVELS),
    _ref("overhead_clear",
         "A high, deep shot hit from an overhead position to push the opponent to the back of the court.",
         [("Preparation", "Turn side-on, racket up, non-hitting arm points at the shuttle to aid balance and timing."),
          ("Loading", "Weight shifts to the back foot, knees bent, shoulders coiled, racket dropped behind the back."),
          ("Contact", "Reach up and slightly in front of the head at full arm extension, forearm pronates through contact."),
          ("Follow-through", "Racket continues down across the body; front foot lands to absorb momentum."),
          ("Recovery", "Push off the front foot back toward center, racket back to neutral.")],
         ["Contact point drifting behind the head, reducing reach and depth.", "Hitting flat-footed without weight transfer.", "Slow recovery back to center."],
         ["Jump clear to take the shuttle earlier.", "Slice clear for disguise at the cost of some depth."],
         checkpoints=["Side-on shoulder turn", "Non-racket arm up", "Contact above/in front of head", "Weight transfer through contact"],
         level_notes=STANDARD_LEVELS),
    _ref("backhand_clear",
         "A rear-court backhand hit deep to the opponent's baseline — one of the hardest strokes to time well.",
         [("Turn & travel", "Turn your back partially to the net, lead with the racket-side foot to the corner."),
          ("Preparation", "Elbow up and bent, thumb braced on the wide grip bevel."),
          ("Contact", "As high as reachable, slightly in front of the shoulder — power comes from forearm supination, not arm swing."),
          ("Recovery", "Push back off the racket-side leg, turning back to face the court.")],
         ["Letting the shuttle drop too low before contact.", "Swinging with the whole arm instead of forearm rotation.", "No thumb support on the grip."],
         ["Backhand drop from identical preparation when the clear isn't needed."],
         checkpoints=["Elbow leads and stays up", "Thumb-supported grip", "Contact ahead of shoulder", "Supination for power"],
         level_notes={**STANDARD_LEVELS, "beginner": "Prefer the around-the-head forehand when possible — build the backhand clear gradually from mid-court feeds."}),
    _ref("forehand_drop",
         "A soft overhead shot from clear/smash preparation that falls just past the net.",
         [("Disguise", "Identical preparation to your clear and smash — same turn, same racket drop."),
          ("Contact", "High contact, but the racket decelerates — slicing or gently guiding the shuttle."),
          ("Trajectory", "Falls between the net and front service line, tight to the tape if possible."),
          ("Recovery", "Move in a step after the drop — anticipate the net reply.")],
         ["Slowing the swing visibly early, telegraphing the drop.", "Hitting it too high and deep — a 'drop' landing mid-court is a free attack."],
         ["Sliced drop (faster, flatter).", "Reverse slice for cross-court deception."],
         checkpoints=["Same preparation as clear/smash", "High contact", "Lands inside front service line"],
         level_notes=STANDARD_LEVELS),
    _ref("backhand_drop",
         "A controlled backhand from the rear corner dropping short — the safer, higher-percentage backhand option.",
         [("Travel & turn", "Same footwork as the backhand clear — racket-side foot leads."),
          ("Contact", "High as reachable, gentle guiding contact with a firm wrist."),
          ("Placement", "Straight drop is safest; cross-court needs disguise or it invites interception."),
          ("Recovery", "Turn and push back toward base watching the net reply.")],
         ["Dropping cross-court without disguise.", "Contact too low, floating the shuttle up."],
         ["Deceptive double-motion for advanced players."],
         checkpoints=["High contact", "Firm wrist, soft hands", "Straight placement default"],
         level_notes=STANDARD_LEVELS),
    _ref("smash",
         "A steep, powerful attacking shot hit downward from an overhead position.",
         [("Preparation", "Same side-on shoulder turn as the clear, disguising intent."),
          ("Loading", "Optional jump takes the shuttle earlier and steeper; legs and trunk coil."),
          ("Contact", "Highest comfortable point, slightly in front of the body, full pronation snapping the shuttle down."),
          ("Landing", "Balanced landing absorbing impact through the knees."),
          ("Recovery", "Immediate recovery toward mid-court — expect a fast defensive return.")],
         ["Rushing preparation, telegraphing the smash.", "Contact behind the body, flattening the angle.", "Watching the smash instead of recovering."],
         ["Around-the-head smash.", "Half-smash / stick smash for steepness with control."],
         checkpoints=["High contact in front", "Full pronation", "Balanced landing", "Instant recovery"],
         level_notes=STANDARD_LEVELS,
         context_notes={"attacking": "In doubles, smash mostly straight or at the body — cross-court smashes get intercepted.",
                        "rear_court": "From the deep corners, favor the half-smash: full smashes from the baseline sit up."}),
    _ref("jump_smash",
         "A smash with a scissor-kick jump for earlier, steeper contact — an advanced weapon with a fitness cost.",
         [("Approach", "Get behind the shuttle first — the jump goes up, not backward."),
          ("Scissor jump", "Legs scissor mid-air: racket-side leg swings from back to front."),
          ("Contact", "At the top of the jump, in front of the body, maximum pronation."),
          ("Landing", "Land on the non-racket leg first, already moving forward."),
          ("Recovery", "The landing flows directly into your first recovery step.")],
         ["Jumping while still behind the shuttle, forcing contact behind the head.", "Unbalanced landings that delay recovery by half a second."],
         ["Directional disguise at the top of the jump."],
         checkpoints=["Behind the shuttle before jumping", "Scissor timing", "Peak-of-jump contact", "Forward-moving landing"],
         level_notes={**STANDARD_LEVELS, "beginner": "Master the standing smash first — the jump multiplies both power and error."}),
    _ref("drive",
         "A flat, fast exchange shot traveling parallel to the floor at net height.",
         [("Ready", "Racket up in front, elbow away from the body, grip relaxed."),
          ("Contact", "Short punching action in front of the body — no backswing."),
          ("Reset", "Racket returns instantly to the front-up position for the next exchange.")],
         ["Full swings that arrive late in fast exchanges.", "Racket dropping between shots.", "Standing tall — good drives come from a slight crouch."],
         ["Deceptive soft block mixed into drive exchanges."],
         checkpoints=["No backswing", "Contact in front", "Racket never drops"],
         level_notes=STANDARD_LEVELS,
         context_notes={"attacking": "Drive at the receiver's racket shoulder to jam them.",
                        "defensive": "Drive to the open space, not back at the strong player."}),
    _ref("push",
         "A controlled shot pushed flat past the net player, landing mid-court — the doubles rally-builder.",
         [("Preparation", "Taken early in front, short racket lift."),
          ("Contact", "Guided contact aiming past the net player's reach, at hip-height of the rear player."),
          ("Recovery", "Stay low, racket up — the reply comes fast.")],
         ["Pushing too high, giving the rear player a full smash.", "Pushing straight at the net player's racket."],
         ["Push-lob hybrid to the rear corners against tall net players."],
         checkpoints=["Early contact", "Flat trajectory past the net player", "Low ready position after"],
         level_notes=STANDARD_LEVELS, ctx="doubles"),
    _ref("lift",
         "An underarm shot lifted high and deep, converting defense into reset time.",
         [("Base", "Lunge or reach toward the shuttle, racket leg forward."),
          ("Contact", "Under the shuttle out in front, full underarm swing driving it high AND deep."),
          ("Depth check", "A short lift is the worst shot in badminton — depth to the back alley is everything."),
          ("Recovery", "Push back to base while the shuttle is in the air — the height buys you time.")],
         ["Short lifts landing mid-court — free smashes for the opponent.", "Lifting cross-court by default, doubling the opponent's angles."],
         ["Flat attacking lift when the opponent has drifted forward."],
         checkpoints=["Contact in front", "Height + depth together", "Recovery during flight"],
         level_notes=STANDARD_LEVELS),
    _ref("net_shot",
         "A delicate shot from near the net that falls tight to the tape on the opponent's side.",
         [("Approach", "Lunge in with the racket leg, racket reaching before the body arrives."),
          ("Contact", "As early and high as possible, racket face nearly flat, feather-soft grip."),
          ("Spin (advanced)", "Slicing under the shuttle adds tumble, making kills risky."),
          ("Recovery", "Hold a beat — the straight net reply is the most common answer.")],
         ["Hitting from a static reach instead of a stable lunge.", "Gripping tight, popping the shuttle up.", "Recovering before reading the reply."],
         ["Tumbling/spinning net shots.", "Deceptive hold-and-flick from the same reach."],
         checkpoints=["Early high take", "Soft grip", "Stable lunge base", "One-beat hold before recovery"],
         level_notes=STANDARD_LEVELS),
    _ref("net_kill",
         "A sharp downward tap punishing a loose shuttle above tape height at the net.",
         [("Read & pounce", "Recognize the loose net shot early — first step while the shuttle is still rising."),
          ("Contact", "Short tap from the wrist/forearm above tape height, angled down."),
          ("Net discipline", "Kill the shuttle, not the net — a touched net loses the point."),
          ("Reset", "Tap and rebound to ready; no follow-through needed.")],
         ["Full arm swings into the net.", "Waiting for the shuttle to drop below the tape, losing the kill."],
         ["Brush kill (sweeping sideways) when the shuttle is right on the tape."],
         checkpoints=["Above-tape contact", "Wrist tap, not arm swing", "No net touch"],
         level_notes=STANDARD_LEVELS),
    _ref("defensive_block",
         "A soft racket-face block that absorbs a smash and drops it short over the net.",
         [("Stance", "Low, wide defensive base, racket in front at mid-body height."),
          ("Contact", "Minimal movement — angle the face and let the smash's own pace rebound softly."),
          ("Placement", "Short and away from the net player's reach (doubles) or to the open front court (singles)."),
          ("Reset", "Racket straight back to the front-center guard.")],
         ["Swinging at the smash instead of blocking.", "Blocking high, feeding the follow-up kill."],
         ["Counter-drive block against slower smashes."],
         checkpoints=["Low wide base", "Racket face angle, no swing", "Short landing"],
         level_notes=STANDARD_LEVELS),
    _ref("forehand_defense",
         "Defensive returns on the racket side against smashes — block, drive, or lift under pressure.",
         [("Base", "Split low as the smash is struck, racket slightly toward the forehand side."),
          ("Choice", "Block short, drive flat, or lift deep depending on smash steepness and your balance."),
          ("Contact", "In front of the body — jammed contact at the hip is the smasher's goal, deny it."),
          ("Reset", "Return to center guard before the next attack.")],
         ["Racket held too low to react.", "Always lifting, inviting endless smashes."],
         ["Counter-attack drives off weaker smashes."],
         checkpoints=["Pre-smash split", "Contact in front", "Choice varies by pressure"],
         level_notes=STANDARD_LEVELS),
    _ref("backhand_defense",
         "Defensive returns across the body — the backhand grip guards most of the body under smash fire.",
         [("Guard", "Backhand grip as default under attack — it covers the body and both hips fastest."),
          ("Contact", "Thumb-supported push in front of the torso."),
          ("Placement", "Same triangle: block short, drive flat, lift deep."),
          ("Reset", "Guard returns to front-center.")],
         ["Switching to forehand grip mid-exchange and getting jammed.", "Contact against the body instead of in front."],
         ["Two-handed emergency defense on extreme body smashes."],
         checkpoints=["Backhand guard by default", "Thumb support", "In-front contact"],
         level_notes=STANDARD_LEVELS),
    _ref("split_step",
         "A small preparatory hop landing just before opponent contact — the engine of court speed.",
         [("Timing", "Initiate so your feet land at or a fraction before the opponent strikes the shuttle."),
          ("Shape", "Feet shoulder-width, knees soft, weight on the balls of the feet."),
          ("Launch", "The landing loads your legs — the first step fires off that elastic energy.")],
         ["Splitting after opponent contact — the most common speed leak at club level.", "Landing flat-footed or too upright."],
         ["Directional pre-loading based on reading the opponent's options."],
         category="movement",
         checkpoints=["Lands at/just before opponent contact", "Shoulder-width, soft knees", "Immediate first step"],
         level_notes=STANDARD_LEVELS),
    _ref("net_lunge",
         "The forecourt lunge pattern for reaching net shots with stability and quick exit.",
         [("Split step", "Timed split as the opponent plays short."),
          ("First step", "Push from the back leg; racket begins reaching immediately."),
          ("Lunge", "Racket-side foot lands heel-first, pointed at the shuttle, knee tracking over toes."),
          ("Contact", "Reach with the racket arm, torso upright — don't dive with the head."),
          ("Push-off", "The front leg pushes you straight back out — no extra gather step.")],
         ["Lunge foot landing too narrow, wobbling the base.", "Torso collapsing forward over the front knee.", "Standing up before pushing back."],
         ["Deeper kill-step lunge when attacking loose shuttles."],
         category="movement",
         checkpoints=["Heel-first landing", "Knee over toes", "Upright torso", "Single push-off exit"],
         level_notes=STANDARD_LEVELS),
    _ref("rear_court_movement",
         "Footwork to the rear corners: chassé and cross-over patterns that arrive behind the shuttle.",
         [("Split & turn", "Split step, then hip turn toward the corner — shoulders go side-on early."),
          ("Travel", "Chassé steps for shorter distances; cross-over behind for the deep corner."),
          ("Arrive behind", "The last step puts the shuttle in FRONT of your hitting shoulder."),
          ("Hit & scissor", "Weight transfers back-to-front (or scissors mid-air) through the shot."),
          ("Recover", "First recovery step is part of the stroke, not after it.")],
         ["Running face-on to the corner, forcing contact behind the head.", "Arriving under the shuttle instead of behind it."],
         ["Jump-out variations for earlier takes."],
         category="movement",
         checkpoints=["Early hip turn", "Arrive behind the shuttle", "Weight transfer through the hit", "Stroke flows into recovery"],
         level_notes=STANDARD_LEVELS),
    _ref("side_to_side_defense",
         "Lateral defensive movement covering drives and smashes to both sides.",
         [("Low base", "Wide stance, racket at mid-height in front, backhand-grip guard."),
          ("Lateral push", "Push off the far leg; small chassé — no crossing feet under fire."),
          ("Contact", "In front of the body line even while moving."),
          ("Re-center", "Small recovery steps back to the middle after each return.")],
         ["Standing tall between shots.", "Crossing legs during fast exchanges — one wrong-footed drive ends the rally."],
         ["Anticipatory lean against predictable attackers."],
         category="movement",
         checkpoints=["Stay low throughout", "No crossed feet", "In-front contact while moving"],
         level_notes=STANDARD_LEVELS),
    _ref("doubles_rotation",
         "The front-back ↔ side-by-side rotation system that keeps a doubles pair covering the right space.",
         [("Attack shape", "Your team attacking = front-back: one player at the net, one covering the rear."),
          ("Defense shape", "Your team defending = side-by-side: each covers a half against the smash."),
          ("Trigger: lift by you", "You lifted = you're defending: rotate to side-by-side as the shuttle rises."),
          ("Trigger: attack regained", "Opponent lifts = attack: the player nearer the net takes it, partner drops behind."),
          ("Continuous flow", "Rotation follows the shuttle's height: down = attack shape, up = defense shape.")],
         ["Both players ball-watching in a line (front-back during defense).", "Net player retreating for shots the rear player owns.", "Nobody claiming the middle channel during drives."],
         ["Channel attack rotations.", "Serve-and-rush patterns off the low serve."],
         category="movement", ctx="doubles",
         checkpoints=["Shape matches attack/defense state", "Rotation triggered by shuttle height", "Middle channel owned"],
         level_notes=STANDARD_LEVELS,
         context_notes={"attacking": "Rear player smashes straight; net player covers the block — the pair moves as a unit.",
                        "defensive": "Defend cross-court to move the attack away, then rotate on the lift."}),
    _ref("singles_recovery",
         "Recovery movement back to a dynamic base position between singles shots.",
         [("Base, not center", "Recover toward a base biased by your last shot — straight drop = base slightly toward that side."),
          ("Move during flight", "Recovery happens while the shuttle travels — arriving as the opponent hits."),
          ("Arrive in split", "Time the recovery so you land in your split step at their contact."),
          ("Never spectate", "Watching your own good shot for even half a second concedes the next corner.")],
         ["Recovering to dead-center regardless of shot played.", "Full stop at base before splitting again."],
         ["Aggressive base positioning against weaker opponents."],
         category="movement", ctx="singles",
         checkpoints=["Shot-biased base", "Recovery during shuttle flight", "Arrive into the split step"],
         level_notes=STANDARD_LEVELS),
]

DRILLS = [
    {"name": "Shadow split-step timing", "category": "footwork", "description": "Partner feeds random shots on a verbal cue; player split-steps on the cue, not on shuttle flight, to build earlier reaction timing.", "target_issue_tags": ["split_step_timing", "reaction_speed"], "difficulty": "all_levels"},
    {"name": "Mirror clear contact-point check", "category": "technique", "description": "Shadow-swing overhead clears in front of a mirror or phone camera, checking the contact point is above and slightly in front of the head before hitting live shuttles.", "target_issue_tags": ["clear_contact_point", "overhead_technique"], "difficulty": "beginner_to_intermediate"},
    {"name": "Net-shot-then-hold recovery", "category": "positioning", "description": "Play a tight net shot, hold position for one beat instead of recovering immediately, then react to the opponent's actual reply direction.", "target_issue_tags": ["early_recovery", "net_positioning"], "difficulty": "intermediate_to_advanced"},
    {"name": "Front-back / side-by-side rotation (doubles)", "category": "tactics", "description": "Practice transitioning between front-back attacking formation and side-by-side defensive formation, cued by whether the team is attacking or defending.", "target_issue_tags": ["doubles_formation"], "difficulty": "intermediate_to_advanced"},
    {"name": "Lunge landing width ladder", "category": "footwork", "description": "Practice lunges to cones set at varying widths, focusing on foot direction matching the direction of travel for a stable base.", "target_issue_tags": ["lunge_stability", "net_footwork"], "difficulty": "all_levels"},
    {"name": "Jump smash landing control", "category": "technique", "description": "Practice jump smashes focusing on a balanced landing that flows into the first recovery step, rather than recovering after regaining balance.", "target_issue_tags": ["smash_landing", "balance_recovery"], "difficulty": "advanced"},
    {"name": "Fast drive exchange", "category": "technique", "description": "Two players exchange flat drives from mid-court, focusing on keeping the racket up between shots rather than dropping it during recovery.", "target_issue_tags": ["drive_recovery", "racket_preparation"], "difficulty": "intermediate_to_advanced"},
    {"name": "Corner-to-corner endurance rally", "category": "endurance", "description": "Continuous rallying to all four corners to build movement endurance and consistency under fatigue.", "target_issue_tags": ["stamina", "movement_consistency"], "difficulty": "all_levels"},
    {"name": "Multi-shuttle lift depth", "category": "technique", "description": "Coach feeds smashes/drops; player lifts every shuttle past a rope hung 1m inside the baseline — trains depth under pressure.", "target_issue_tags": ["lift_depth", "defensive_consistency"], "difficulty": "all_levels"},
    {"name": "Serve + first-three-shots pattern", "category": "tactics", "description": "Play only the serve and next three shots repeatedly, rehearsing your chosen opening patterns until they're automatic.", "target_issue_tags": ["serve_quality", "pattern_predictability"], "difficulty": "intermediate_to_advanced"},
    {"name": "Deception hold at the net", "category": "technique", "description": "From the same net-reach preparation, alternate randomly between tight net shots and flick lifts on a partner's call.", "target_issue_tags": ["shot_variety", "pattern_predictability", "net_positioning"], "difficulty": "advanced"},
    {"name": "Half-court singles pressure", "category": "endurance", "description": "Singles on half the court width — more shots per minute, faster recovery demands, ideal for movement-efficiency work.", "target_issue_tags": ["movement_consistency", "early_recovery", "stamina"], "difficulty": "all_levels"},
]


def seed():
    Base.metadata.create_all(engine)
    db = SessionLocal()
    try:
        for tr in TECHNIQUE_REFERENCES:
            existing = db.query(TechniqueReference).filter_by(shot_or_movement_name=tr["shot_or_movement_name"]).first()
            if not existing:
                db.add(TechniqueReference(**tr))
            else:
                for key, value in tr.items():
                    setattr(existing, key, value)
        for d in DRILLS:
            existing = db.query(Drill).filter_by(name=d["name"]).first()
            if not existing:
                db.add(Drill(**d))
        db.commit()
        print(f"Seeded {len(TECHNIQUE_REFERENCES)} technique references and {len(DRILLS)} drills.")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
